# Generated by Django 6.0.1 on 2026-02-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('manage_products', 'can manage products')]},
        ),
    ]
