# Generated by Django 6.0.1 on 2026-02-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('view_categories', 'can view categories')]},
        ),
    ]
